### ISSUE TITLE
User preferences and profile

### ISSUE THREAD

**Issue by sr229** [Sayo-nika/Frontend#15]
Currently profile in Frontend does not reflect user info in backend, we need to set this properly.

## TODO

- [ ] Profile bio, username, and badges should reflect their respective user data.
- [ ] Allow people to set their profile picture via Settings
- [ ] Allow people to also change their username if need be
