### ISSUE TITLE
Admin Dashboard backlog

### ISSUE THREAD

**Issue by sr229** [Sayo-nika/Frontend#16]
Currently Admin dashboard is a big heckin chonk of a template. We need to finish it by next week so we can onboard everyone

## TODO
- [ ] Live data on Home
- [ ] Report Queue (Mods and Users)
- [ ] Pending Mods
- [ ] User Access Control (Deleting and setting the properties of a user)

**Comment by Ovyerus** [comment]
Mostly waiting on report stuff now.

**Comment by sr229** [comment]
Can we do a test release today under `sayonika.moe` without reporting so we can see if there's any bugs going by? @Ovyerus

**Comment by sr229** [comment]
Resetting progress for this issue due to re-assignment to Reactify
